In [51]:
import sys
import subprocess
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score

try:
    from xgboost import XGBRegressor
except ModuleNotFoundError:
    subprocess.check_call([sys.executable, "-m", "pip", "install", "xgboost"])
    from xgboost import XGBRegressor

# Load dataset and keep an untouched copy for repeatable mappings
df_raw = pd.read_csv("crop_dataset.csv")
df = df_raw.copy()

In [86]:
df.columns

Index(['State', 'District', 'Market', 'Commodity', 'Variety', 'Grade',
       'Arrival_Date', 'Min_x0020_Price', 'Max_x0020_Price',
       'Modal_x0020_Price', 'City', 'Crop Type', 'Season',
       'Temperature (degree C)', 'Rainfall (mm)', 'Supply Volume (tons)',
       'Demand Volume (tons)', 'Transportation Cost (₹/ton)',
       'Fertilizer Usage (kg/hectare)', 'Pest Infestation (0-1)',
       'Market Competition (0-1)', 'Price (₹/ton)'],
      dtype='object')

In [48]:
# Drop the 'Unnamed: 0' and 'Date' columns
df = df.drop(columns=['Unnamed: 0', 'Date'], errors='ignore')

In [87]:
df.isnull().sum()

State                            0
District                         0
Market                           0
Commodity                        0
Variety                          0
Grade                            0
Arrival_Date                     0
Min_x0020_Price                  0
Max_x0020_Price                  0
Modal_x0020_Price                0
City                             0
Crop Type                        0
Season                           0
Temperature (degree C)           0
Rainfall (mm)                    0
Supply Volume (tons)             0
Demand Volume (tons)             0
Transportation Cost (₹/ton)      0
Fertilizer Usage (kg/hectare)    0
Pest Infestation (0-1)           0
Market Competition (0-1)         0
Price (₹/ton)                    0
dtype: int64

In [88]:
# Identify object-type columns in the current dataframe
object_cols = df.select_dtypes(include=["object"]).columns

# Build mappings only when object columns are present
if len(object_cols) > 0:
    mappings = {}

    for col in object_cols:
        # Sort values for stable mapping and skip missing values
        unique_values = sorted(df[col].dropna().unique())
        mapping = {value: idx for idx, value in enumerate(unique_values)}

        # Store mapping and apply encoding
        mappings[col] = mapping
        df[col] = df[col].map(mapping)

# Print mappings if available (works even after re-running cells)
if "mappings" in globals() and len(mappings) > 0:
    for col, mapping in mappings.items():
        print(f"Mapping for {col}:")
        for value, idx in mapping.items():
            print(f"  {value}: {idx}")
        print()
else:
    print("No object-type columns found and no previous mappings available.")

Mapping for State:
  Andhra Pradesh: 0
  Assam: 1
  Bihar: 2
  Chandigarh: 3
  Gujarat: 4
  Haryana: 5
  Himachal Pradesh: 6
  Kerala: 7
  Madhya Pradesh: 8
  Nagaland: 9
  Odisha: 10
  Punjab: 11
  Rajasthan: 12
  Tamil Nadu: 13
  Telangana: 14
  Tripura: 15
  Uttar Pradesh: 16
  Uttarakhand: 17
  West Bengal: 18

Mapping for District:
  Adilabad: 0
  Ahmedabad: 1
  Ajmer: 2
  Alappuzha: 3
  Aligarh: 4
  Alwar: 5
  Amreli: 6
  Amritsar: 7
  Annamayya: 8
  Ariyalur: 9
  Badaun: 10
  Badwani: 11
  Bahraich: 12
  Balrampur: 13
  Bargarh: 14
  Beawar: 15
  Bhadradri Kothagudem: 16
  Bhatinda: 17
  Bhiwani: 18
  Bikaner: 19
  Birbhum: 20
  Boudh: 21
  Chamba: 22
  Chandigarh: 23
  Chengalpattu: 24
  Chhota Udaipur: 25
  Chittor: 26
  Chittorgarh: 27
  Churu: 28
  Coimbatore: 29
  Coochbehar: 30
  Cuddalore: 31
  Cuttack: 32
  Darjeeling: 33
  Deeg: 34
  Dehradoon: 35
  Dhar: 36
  Dharmapuri: 37
  Dhenkanal: 38
  East Champaran/ Motihari: 39
  East Godavari: 40
  Ernakulam: 41
  Erode: 42
  Etah: 43
  Faridabad: 44
  Faridkot: 45
  Farukhabad: 46
  Fatehpur: 47
  Fazilka: 48
  Ferozpur: 49
  Ganganagar: 50
  Ghazipur: 51
  Gir Somnath: 52
  Gomati: 53
  Gurgaon: 54
  Hamirpur: 55
  Hanumangarh: 56
  Haridwar: 57
  Hathras: 58
  Hissar: 59
  Hoshiarpur: 60
  Idukki: 61
  Jabalpur: 62
  Jagatsinghpur: 63
  Jalandhar: 64
  Jalaun (Orai): 65
  Jalore: 66
  Jhajar: 67
  Jhargram: 68
  Jharsuguda: 69
  Jhunjhunu: 70
  Jodhpur: 71
  Junagarh: 72
  Kaithal: 73
  Kalahandi: 74
  Kallakuruchi: 75
  Kancheepuram: 76
  Kangra: 77
  Kannur: 78
  Karimnagar: 79
  Karur: 80
  Kaushambi: 81
  Khammam: 82
  Khandwa: 83
  Khiri (Lakhimpur): 84
  Khowai: 85
  Kohima: 86
  Kota: 87
  Kottayam: 88
  Kozhikode(Calicut): 89
  Krishnagiri: 90
  Kullu: 91
  Kurukshetra: 92
  Ludhiana: 93
  Madurai: 94
  Maharajganj: 95
  Mahbubnagar: 96
  Mahendragarh-Narnaul: 97
  Malappuram: 98
  Malda: 99
  Mandi: 100
  Mau(Maunathbhanjan): 101
  Mayurbhanja: 102
  Medinipur(E): 103
  Mehsana: 104
  Mewat: 105
  Moga: 106
  Mohali: 107
  Muktsar: 108
  Murshidabad: 109
  Nagaon: 110
  Nagapattinam: 111
  Nagercoil (Kannyiakumari): 112
  Nalgonda: 113
  Namakkal: 114
  Nanital: 115
  Narmada: 116
  Nellore: 117
  Palakad: 118
  Pali: 119
  Palnadu: 120
  Panchkula: 121
  Panipat: 122
  Pathanamthitta: 123
  Perambalur: 124
  Pudukkottai: 125
  Raebarelli: 126
  Rajkot: 127
  Rajsamand: 128
  Ramanathapuram: 129
  Ranipet: 130
  Rayagada: 131
  Rewa: 132
  Rewari: 133
  Rohtak: 134
  Rohtas: 135
  Ropar (Rupnagar): 136
  Sabarkantha: 137
  Sagar: 138
  Saharanpur: 139
  Salem: 140
  Sambalpur: 141
  Sambhal: 142
  Sangrur: 143
  Sant Kabir Nagar: 144
  Sepahijala: 145
  Shamli: 146
  Sheopur: 147
  Sirmore: 148
  Sirsa: 149
  Sitapur: 150
  Sivaganga: 151
  Solan: 152
  Sonipat: 153
  South Tripura: 154
  Sundergarh: 155
  Surat: 156
  Tarntaran: 157
  Thanjavur: 158
  The Nilgiris: 159
  Theni: 160
  Thirssur: 161
  Thiruchirappalli: 162
  Thirunelveli: 163
  Thirupathur: 164
  Thirupur: 165
  Thiruvananthapuram: 166
  Thiruvannamalai: 167
  Thiruvarur: 168
  Thiruvellore: 169
  Tuticorin: 170
  Udhamsinghnagar: 171
  Una: 172
  Vadodara(Baroda): 173
  Valsad: 174
  Vellore: 175
  Villupuram: 176
  Virudhunagar: 177
  Warangal: 178
  Wayanad: 179
  West Godavari: 180
  Yamuna Nagar: 181

Mapping for Market:
  AJattihalli(Uzhavar Sandhai ) APMC: 0
  APMCKHEDBRAHMA: 1
  Adilabad APMC: 2
  Ahmedgarh APMC: 3
  Ait APMC: 4
  Alangudi(Uzhavar Sandhai ) APMC: 5
  Ambagan APMC: 6
  Ambasamudram(Uzhavar Sandhai ) APMC: 7
  Ammapet(Uzhavar Sandhai ) APMC: 8
  Anandnagar APMC: 9
  Andipatti(Uzhavar Sandhai ) APMC: 10
  Angadippuram VFPCK APMC: 11
  Angamaly APMC: 12
  Anna nagar(Uzhavar Sandhai ) APMC: 13
  Aralamoodu APMC: 14
  Arani(Uzhavar Sandhai ) APMC: 15
  Aranthangi(Uzhavar Sandhai ) APMC: 16
  Arcot(Uzhavar Sandhai ) APMC: 17
  Ariyalur(Uzhavar Sandhai) APMC: 18
  Aruppukottai(Uzhavar Sandhai ) APMC: 19
  Athirampuzha APMC: 20
  Attabira APMC: 21
  Attayampatti(Uzhavar Sandhai ) APMC: 22
  Avallapalli(Uzhavar Sandhai ) APMC: 23
  Avalurpet APMC: 24
  Awagarh APMC: 25
  Babain APMC: 26
  Babrala APMC: 27
  Bachranwa APMC: 28
  Bagasara APMC: 29
  Baghapurana APMC: 30
  Ballabhgarh APMC: 31
  Banki APMC: 32
  Barwala APMC: 33
  Barwala(Hisar) APMC: 34
  Betnoti APMC: 35
  Bharwari APMC: 36
  Bhehjoi APMC: 37
  Bhesan APMC: 38
  Bhiwani APMC: 39
  Bhogpur APMC: 40
  Bhucho APMC: 41
  Bijaynagar APMC: 42
  Bikaner (Grain) APMC: 43
  Birbhum APMC: 44
  Bisoli APMC: 45
  Bodeliu APMC: 46
  Bodinayakanur(Uzhavar Sandhai ) APMC: 47
  Bolpur APMC: 48
  Bonai APMC: 49
  Boudh APMC: 50
  Chakia APMC: 51
  Chala APMC: 52
  Chandigarh(Grain/Fruit) APMC: 53
  Charra APMC: 54
  Chengalpet(Uzhavar Sandhai ) APMC: 55
  Chengannur APMC: 56
  Cherthala APMC: 57
  Cheyyar(Uzhavar Sandhai ) APMC: 58
  Chhachrauli APMC: 59
  Chidambaram(Uzhavar Sandhai ) APMC: 60
  Chikli(Khorgam) APMC: 61
  Chinnamanur(Uzhavar Sandhai ) APMC: 62
  Chittoor APMC: 63
  Chokkikulam(Uzhavar Sandhai ) APMC: 64
  Churu APMC: 65
  Cuddalore(Uzhavar Sandhai ) APMC: 66
  Dammapet APMC: 67
  Darjeeling APMC: 68
  Denduluru APMC: 69
  Denkanikottai(Uzhavar Sandhai ) APMC: 70
  Devakottai (Uzhavar Sandhai ) APMC: 71
  Devarakonda APMC: 72
  Devaram(Uzhavar Sandhai ) APMC: 73
  Dhand APMC: 74
  Dharapuram(Uzhavar Sandhai ) APMC: 75
  Dharmapuri(Uzhavar Sandhai ) APMC: 76
  Dhing APMC: 77
  Dholka APMC: 78
  Dhoraji APMC: 79
  Doomdumia APMC: 80
  Doraha APMC: 81
  Edackattuvayal  VFPCK APMC: 82
  Edapadi (Uzhavar Sandhai ) APMC: 83
  Elamkulam VFPCK APMC: 84
  Elampillai(Uzhavar Sandhai ) APMC: 85
  Farukh Nagar APMC: 86
  Fazilka APMC: 87
  FerozpurZirkha(Nagina) APMC: 88
  Gandarvakottai(Uzhavar Sandhai ) APMC: 89
  Gandhigramam(Uzhavar Sandhai): 90
  Gangoh APMC: 91
  Garh Shankar APMC: 92
  GarhShankar (Kotfatuhi) APMC: 93
  Garhakota APMC: 94
  Gingee(Uzhavar Sandhai ) APMC: 95
  Gobichettipalayam(Uzhavar Sandhai ) APMC: 96
  Gohana APMC: 97
  Goluwala APMC: 98
  Gondal(Veg.market Gondal) APMC: 99
  Govindgarh APMC: 100
  Gudalur(Uzhavar Sandhai ) APMC: 101
  Gudiyatham(Uzhavar Sandhai ) APMC: 102
  Guduvancheri(Uzhavar Sandhai ) APMC: 103
  Gummidipoondy APMC: 104
  Gunpur APMC: 105
  Gurazala APMC: 106
  Gurgaon APMC: 107
  Hadad     APMC: 108
  Haibargaon APMC: 109
  Haldwani APMC: 110
  Hansi APMC: 111
  Hanumana(F&V) APMC: 112
  Hargaon (Laharpur) APMC: 113
  Haridwar Union APMC: 114
  Harsood APMC: 115
  Harur(Uzhavar Sandhai ) APMC: 116
  Hasthampatti(Uzhavar Sandhai ) APMC: 117
  Hosur(Uzhavar Sandhai ) APMC: 118
  Huzzurabad APMC: 119
  Jabalpur APMC: 120
  Jalagandapuram(Uzhavar Sandhai ) APMC: 121
  Jalalabad APMC: 122
  Jalaun APMC: 123
  Jalore APMC: 124
  Jamanian APMC: 125
  Jasdan(Vichhiya) APMC: 126
  Jetpur(Dist.Rajkot) APMC: 127
  Jhajjar APMC: 128
  Jhargram APMC: 129
  Jharsuguda APMC: 130
  Jiaganj APMC: 131
  Jodhpur (F&V) APMC: 132
  Junagarh APMC: 133
  Kadukutty VFPCK APMC: 134
  Kahithapattarai(Uzhavar Sandhai ) APMC: 135
  Kairana APMC: 136
  Kalediya APMC: 137
  Kalikiri APMC: 138
  Kallachi APMC: 139
  Kallakurichi(Uzhavar Sandhai ) APMC: 140
  Kamakhyanagar APMC: 141
  Kambam(Uzhavar Sandhai ) APMC: 142
  Kamlaganj APMC: 143
  Kamuthi(Uzhavar Sandhai ) APMC: 144
  Kandiyaperi(Uzhavar Sandhai ) APMC: 145
  Kangayam(Uzhavar Sandhai ) APMC: 146
  Kannur APMC: 147
  Kapasan APMC: 148
  Karaikudi(Uzhavar Sandhai ) APMC: 149
  Karalam VFPCK APMC: 150
  Karimangalam(Uzhavar Sandhai): 151
  Kariyapatti(Uzhavar Sandhai ) APMC: 152
  Karsiyang(Matigara) APMC: 153
  Karur(Uzhavar Sandhai ) APMC: 154
  Kattakada APMC: 155
  Kattampak  VFPCK APMC: 156
  Kattappana APMC: 157
  Khalilabad APMC: 158
  Kicchha APMC: 159
  Kishunpur APMC: 160
  Kohima APMC: 161
  Kolaghat APMC: 162
  Konch APMC: 163
  Kopaganj APMC: 164
  Kosli APMC: 165
  Kota APMC: 166
  Kotkapura APMC: 167
  Kottakkal APMC: 168
  Kovilnada  VFPCK APMC: 169
  Kovilpatti(Uzhavar Sandhai ) APMC: 170
  Krishnagiri(Uzhavar Sandhai ) APMC: 171
  Kulithalai(Uzhavar Sandhai ) APMC: 172
  Kumarapalayam(Uzhavar Sandhai ) APMC: 173
  Kumbakonam (Uzhavar Sandhai ) APMC: 174
  Kundrathur(Uzhavar Sandhai ) APMC: 175
  Kurali APMC: 176
  Kurichi(Uzhavar Sandhai ) APMC: 177
  Lalganj APMC: 178
  Lalgudi(Uzhavar Sandhai ) APMC: 179
  Lalru APMC: 180
  Ludhiana APMC: 181
  Madanapalli APMC: 182
  Madanganj Kishangarh APMC: 183
  Madhuranthagam(Uzhavar Sandhai ) APMC: 184
  Maigalganj APMC: 185
  Manachanallur(Uzhavar Sandhai ) APMC: 186
  Manapparai(Uzhavar Sandhai ) APMC: 187
  Manglaur APMC: 188
  Mankada VFPCK APMC: 189
  Mannar APMC: 190
  Mannargudi I(Uzhavar Sandhai ) APMC: 191
  Mannargudi II(Uzhavar Sandhai ) APMC: 192
  Manubazar: 193
  Marottichal  VFPCK APMC: 194
  Mathabhanga APMC: 195
  Mayiladuthurai(Uzhavar Sandhai ) APMC: 196
  Mecheri(Uzhavar Sandhai): 197
  Meghraj APMC: 198
  Meham APMC: 199
  Mehatpur APMC: 200
  Mehsana(Jornang) APMC: 201
  Melaghar APMC: 202
  Melapalayam(Uzhavar Sandhai ) APMC: 203
  Melur(Uzhavar Sandhai ) APMC: 204
  Mettupalayam(Uzhavar Sandhai ) APMC: 205
  Mettur(Uzhavar Sandhai ) APMC: 206
  Modasar APMC: 207
  Moga APMC: 208
  Mohanur(Uzhavar Sandhai ) APMC: 209
  Morinda APMC: 210
  Muktsar APMC: 211
  Musiri(Uzhavar Sandhai ) APMC: 212
  NGO Colony(Uzhavar Sandhai ) APMC: 213
  Naanpara APMC: 214
  Nagapattinam(Uzhavar Sandhai ) APMC: 215
  Namakkal(Uzhavar Sandhai ) APMC: 216
  Nanakmatta APMC: 217
  Narasinghpur APMC: 218
  Narnaul APMC: 219
  Natrampalli(Uzhavar Sandhai ) APMC: 220
  Natwar APMC: 221
  Needamangalam(Uzhavar Sandhai ) APMC: 222
  Nizar(Kukarmuda) APMC: 223
  Nuguru Charla APMC: 224
  Nutanbazar APMC: 225
  PMY Chamba: 226
  PMY Hamirpur: 227
  PMY Kangra: 228
  PMY Kather Solan: 229
  PMY Paonta Sahib: 230
  Padra APMC: 231
  Pala APMC: 232
  Palacode(Uzhavar Sandhai ) APMC: 233
  Palanganatham(Uzhavar Sandhai ) APMC: 234
  Palayam APMC: 235
  Palayamkottai(Uzhavar Sandhai ) APMC: 236
  Palladam(Uzhavar Sandhai ) APMC: 237
  Pallapatti (Uzhavar Sandhai ) APMC: 238
  Pallavaram(Uzhavar Sandhai ) APMC: 239
  Pallikkal  VFPCK APMC: 240
  Pallikkal VFPCK APMC: 241
  Pampady APMC: 242
  Panchpedwa APMC: 243
  Panipat APMC: 244
  Pappanchani VFPCK APMC: 245
  Paramakudi(Uzhavar Sandhai ) APMC: 246
  Paramathivelur(Uzhavar Sandhai ) APMC: 247
  Pataudi APMC: 248
  Pattambi APMC: 249
  Patti APMC: 250
  Pattukottai(Uzhavar Sandhai ) APMC: 251
  Payyannur APMC: 252
  Pennagaram(Uzhavar Sandhai ) APMC: 253
  Perambalur(Uzhavar Sandhai ) APMC: 254
  Perampet(Uzhavar Sandhai): 255
  Periyakulam(Uzhavar Sandhai ) APMC: 256
  Periyar Nagar(Uzhavar Sandhai ) APMC: 257
  Perumbavoor APMC: 258
  Perundurai(Uzhavar Sandhai ) APMC: 259
  Phillaur(Apra Mandi) APMC: 260
  Pipli APMC: 261
  Pollachi(Uzhavar Sandhai ) APMC: 262
  Polur(Uzhavar Sandhai ) APMC: 263
  Ponnamaravathi(Uzhavar Sandhai): 264
  Pudukottai(Uzhavar Sandhai ) APMC: 265
  Pulpally APMC: 266
  Punganur APMC: 267
  Quilandy APMC: 268
  RSPuram(Uzhavar Sandhai ) APMC: 269
  Rahama APMC: 270
  Rairakhol APMC: 271
  Rairangpur APMC: 272
  Rajgarh APMC: 273
  Rajkot(Veg.Sub Yard) APMC: 274
  Rajpipla APMC: 275
  Rajsamand APMC: 276
  Ramanathapuram(Uzhavar Sandhai ) APMC: 277
  Ranipettai(Uzhavar Sandhai ) APMC: 278
  Rasipuram(Uzhavar Sandhai ) APMC: 279
  Ravulapelem APMC: 280
  Rawatsar APMC: 281
  Rayagada APMC: 282
  Rayya APMC: 283
  Rewari APMC: 284
  Rohtak APMC: 285
  Roorkee APMC: 286
  Rudrapur APMC: 287
  SMY Baijnath: 288
  SMY Bhuntar: 289
  SMY Dharamshala: 290
  SMY Jaisinghpur: 291
  SMY Nadaun: 292
  SMY Nahan: 293
  SMY Nalagarh: 294
  SMY Palampur: 295
  SMY Santoshgarh: 296
  SMY Takoli: 297
  Sadhaura APMC: 298
  Sahnewal APMC: 299
  Salon APMC: 300
  Samalkha APMC: 301
  Sampath Nagar(Uzhavar Sandhai ) APMC: 302
  Samsi APMC: 303
  Sangriya APMC: 304
  Sankarapuram(Uzhavar Sandhai ) APMC: 305
  Sargipali APMC: 306
  Sarvepalli APMC: 307
  Sathiyamagalam(Uzhavar Sandhai ) APMC: 308
  Sathupally APMC: 309
  Sendhwa(F&V) APMC: 310
  Shadabad APMC: 311
  Sheopurkalan APMC: 312
  Sikri APMC: 313
  Siliguri APMC: 314
  Singampunari(Uzhavar Sandhai ) APMC: 315
  Singanallur(Uzhavar Sandhai ) APMC: 316
  Sirkali(Uzhavar Sandhai ) APMC: 317
  Sitarganj APMC: 318
  Sivakasi(Uzhavar Sandhai ) APMC: 319
  Sohna APMC: 320
  Sojat City APMC: 321
  Songadh APMC: 322
  Songadh(Badarpada) APMC: 323
  Songadh(Umrada) APMC: 324
  Sooramangalam(Uzhavar Sandhai ) APMC: 325
  Sridungargarh APMC: 326
  Sriganganagar (F&V) APMC: 327
  Sulur(Uzhavar Sandhai ) APMC: 328
  Sundarapuram(Uzhavar Sandhai ) APMC: 329
  Surajgarh APMC: 330
  Surat APMC: 331
  Taliparamba APMC: 332
  Tamarainagar(Uzhavar Sandhai ) APMC: 333
  Tamluk (Medinipur E) APMC: 334
  Tauru APMC: 335
  Teliamura APMC: 336
  Thalasserry APMC: 337
  Thalavaipuram(Uzhavar Sandhai ) APMC: 338
  Thalayolaparambu APMC: 339
  Thammampatti (Uzhavar Sandhai ) APMC: 340
  Thathakapatti(Uzhavar Sandhai ) APMC: 341
  Thengamam VFPCK APMC: 342
  Theni(Uzhavar Sandhai ) APMC: 343
  Thirukalukundram(Uzhavar Sandhai ) APMC: 344
  Thirumangalam(Uzhavar Sandhai ) APMC: 345
  Thirupathur APMC: 346
  Thiruvali  VFPCK APMC: 347
  Thottippal VFPCK APMC: 348
  Thrippunithura APMC: 349
  Thuraiyur APMC: 350
  Tindivanam APMC: 351
  Tiruchengode APMC: 352
  Tirupatthur(Uzhavar Sandhai ) APMC: 353
  Tiruppur (North) (Uzhavar Sandhai ) APMC: 354
  Tiruppur (South) (Uzhavar Sandhai ) APMC: 355
  Tiruthani(Uzhavar Sandhai ) APMC: 356
  Tiruthuraipoondi(Uzhavar Sandhai ) APMC: 357
  Tiruvannamalai(Uzhavar Sandhai ) APMC: 358
  Tiruvarur(Uzhavar Sandhai ) APMC: 359
  Udhagamandalam(Uzhavar Sandhai ) APMC: 360
  Udumalpet APMC: 361
  Ulundurpettai APMC: 362
  Usilampatti(Uzhavar Sandhai ) APMC: 363
  Vadakkenchery APMC: 364
  Vadalur(Uzhavar Sandhai ) APMC: 365
  Vadaseri APMC: 366
  Vadavalli(Uzhavar Sandhai ) APMC: 367
  Valangaiman APMC: 368
  Valmikipuram APMC: 369
  Vandavasi(Uzhavar Sandhai ) APMC: 370
  Vaniyamkulam  VFPCK APMC: 371
  Vaniyampadi(Uzhavar Sandhai ) APMC: 372
  Vazhapadi(Uzhavar Sandhai): 373
  Velayuthampalayam(Uzhavar Sandhai ) APMC: 374
  Vengamedu(Uzhavar Sandhai ) APMC: 375
  Vengola  VFPCK APMC: 376
  Veraval APMC: 377
  Vijaypur APMC: 378
  Vikasnagar APMC: 379
  Viralimalai(Uzhavar Sandhai ) APMC: 380
  Virudhunagar(Uzhavar Sandhai ) APMC: 381
  Viruthachalam(Uzhavar Sandhai ) APMC: 382
  Warangal APMC: 383
  Zira APMC: 384
  kalanwali APMC: 385

Mapping for Commodity:
  Amaranthus: 0
  Amla(Nelli Kai): 1
  Amranthas Red: 2
  Apple: 3
  Arecanut(Betelnut/Supari): 4
  Arhar Dal(Tur Dal): 5
  Arhar(Tur/Red Gram)(Whole): 6
  Ashgourd: 7
  Bajra(Pearl Millet/Cumbu): 8
  Banana: 9
  Banana - Green: 10
  Barley(Jau): 11
  Beans: 12
  Beetroot: 13
  Bengal Gram(Gram)(Whole): 14
  Ber(Zizyphus/Borehannu): 15
  Betal Leaves: 16
  Bhindi(Ladies Finger): 17
  Bitter gourd: 18
  Black Gram Dal(Urd Dal): 19
  Black Gram(Urd Beans)(Whole): 20
  Black pepper: 21
  Bottle gourd: 22
  Brinjal: 23
  Cabbage: 24
  Capsicum: 25
  Cardamoms: 26
  Carrot: 27
  Cashewnuts: 28
  Castor Seed: 29
  Cauliflower: 30
  Chikoos(Sapota): 31
  Chili Red: 32
  Chow Chow: 33
  Cluster beans: 34
  Coconut: 35
  Coconut Oil: 36
  Coconut Seed: 37
  Coffee: 38
  Colacasia: 39
  Copra: 40
  Coriander(Leaves): 41
  Corriander seed: 42
  Cotton: 43
  Cowpea(Veg): 44
  Cucumbar(Kheera): 45
  Custard Apple(Sharifa): 46
  Drumstick: 47
  Elephant Yam(Suran)/Amorphophallus: 48
  Field Pea: 49
  Fig(Anjura/Anjeer): 50
  Firewood: 51
  Fish: 52
  French Beans(Frasbean): 53
  Galgal(Lemon): 54
  Garlic: 55
  Ginger(Dry): 56
  Ginger(Green): 57
  Goat: 58
  Gram Raw(Chholia): 59
  Grapes: 60
  Green Avare(W): 61
  Green Chilli: 62
  Green Gram Dal(Moong Dal): 63
  Green Gram(Moong)(Whole): 64
  Green Peas: 65
  Groundnut: 66
  Guar: 67
  Guava: 68
  Gur(Jaggery): 69
  Indian Beans(Seam): 70
  Indian Colza(Sarson): 71
  Jack Fruit(Ripe): 72
  Jasmine: 73
  Jute: 74
  Kakada: 75
  Karbuja(Musk Melon): 76
  Kinnow: 77
  Kiwi Fruit: 78
  Knool Khol: 79
  Leafy Vegetable: 80
  Lemon: 81
  Lime: 82
  Little gourd(Kundru): 83
  Long Melon(Kakri): 84
  Mahedi: 85
  Maize: 86
  Mango: 87
  Mango(Raw-Ripe): 88
  Marigold(Calcutta): 89
  Marigold(loose): 90
  Mashrooms: 91
  Masur Dal: 92
  Methi Seeds: 93
  Methi(Leaves): 94
  Millets: 95
  Mint(Pudina): 96
  Mousambi(Sweet Lime): 97
  Mustard: 98
  Onion: 99
  Onion Green: 100
  Orange: 101
  Paddy(Basmati): 102
  Paddy(Common): 103
  Papaya: 104
  Papaya(Raw): 105
  Pea Pod/Pea Cod/हरी मटर: 106
  Pear(Marasebu): 107
  Peas Wet: 108
  Peas(Dry): 109
  Pegeon Pea(Arhar Fali): 110
  Pigs: 111
  Pineapple: 112
  Pointed gourd(Parval): 113
  Pomegranate: 114
  Potato: 115
  Pumpkin: 116
  Raddish: 117
  Rat Tail Radish(Mogari): 118
  Rice: 119
  Ridgeguard(Tori): 120
  Rose(Local): 121
  Round gourd: 122
  Rubber: 123
  Season Leaves: 124
  Snakeguard: 125
  Soyabean: 126
  Spinach: 127
  Sponge gourd: 128
  Squash(Chappal Kadoo): 129
  Strawberry: 130
  Surat Beans(Papadi): 131
  Sweet Potato: 132
  Sweet Pumpkin: 133
  Tamarind Fruit: 134
  Tapioca: 135
  Taramira: 136
  Tender Coconut: 137
  Thondekai: 138
  Tinda: 139
  Tomato: 140
  Tube Flower: 141
  Tube Rose(Loose): 142
  Turmeric(raw): 143
  Turnip: 144
  Water Melon: 145
  Wheat: 146
  Wood: 147
  Yam(Ratalu): 148

Mapping for Variety:
  1001: 0
  147 Average: 1
  1st Sort: 2
  777 New Ind: 3
  A-1, Green: 4
  Amaranthus: 5
  American: 6
  Amla: 7
  Amorphophallus: 8
  Amruthapani: 9
  Anjura: 10
  Annabesahai: 11
  Apple: 12
  Arabi: 13
  Arhar (Whole): 14
  Arhar Dal(Tur): 15
  Ashgourd: 16
  Average: 17
  Balli/Habbu: 18
  Banana - Green: 19
  Banana - Ripe: 20
  Banana-Organic: 21
  Bean Barbati: 22
  Beans (Whole): 23
  Beetroot: 24
  Bellary: 25
  Ber(Zizyphus): 26
  Besrai: 27
  Bhindi: 28
  Bhushavali(Pacha): 29
  Big: 30
  Big (With Shell): 31
  Big 100 Kg: 32
  Big/Thick: 33
  Bitter Gourd: 34
  Black: 35
  Black Gram Dal: 36
  Bold: 37
  Bottle Gourd: 38
  Brinjal: 39
  Cabbage: 40
  Capsicum: 41
  Carrot: 42
  Castor seed: 43
  Cauliflower: 44
  Chakkarakeli(Red): 45
  Chakkarakeli(White): 46
  Champa: 47
  Chawli Lal: 48
  Chow Chow: 49
  Cluster Beans: 50
  Coconut: 51
  Coconut Seed: 52
  Colacasia: 53
  Common: 54
  Coriander: 55
  Coriander Seed: 56
  Cotton (Unginned): 57
  Cowpea (Veg): 58
  Cucumbar: 59
  Custard Apple(Sharifa): 60
  Dara: 61
  Darjeeling: 62
  Deshi: 63
  Desi: 64
  Desi (Whole): 65
  Desi(Bontha): 66
  Drumstick: 67
  Dry: 68
  Dry F.A.Q.: 69
  Elakki Bale: 70
  Elephant Yam (Suran): 71
  Eucalyptus: 72
  Field Pea: 73
  Fine: 74
  Fine(Basmati): 75
  Firewood: 76
  French Beans (Frasbean): 77
  Galgal(Lemon): 78
  Garlic: 79
  Goat: 80
  Gouard: 81
  Green: 82
  Green Avare (W): 83
  Green Chilly: 84
  Green Ginger: 85
  Green Gram Dal: 86
  Green Peas: 87
  Guaar: 88
  Guava: 89
  Guava Allahabad: 90
  Gwar: 91
  H.B (Unginned): 92
  Hosur Red: 93
  Hybrid: 94
  Hybrid/Local: 95
  I Sort: 96
  I.R. 36: 97
  III: 98
  Indian Beans (Seam): 99
  Indian Colza(Sarson): 100
  Jack Fruit: 101
  Jalander: 102
  Jasmine: 103
  Jyoti: 104
  Kakada: 105
  Karbhuja: 106
  Karpura: 107
  Kasmir/Shimla - II: 108
  Katla(Big): 109
  Kinnow: 110
  Kiwi: 111
  Knool Khol: 112
  Leafy Vegetables: 113
  Lemon: 114
  Lime: 115
  Little gourd (Kundru): 116
  Local: 117
  Local(Raw): 118
  Lokwan: 119
  Lokwan Gujrat: 120
  Long Melon (Kakri): 121
  MCU-5 (A) 31mm FIne: 122
  MTU-1010: 123
  Mahedi: 124
  Mango - Raw-Ripe: 125
  Marigold(Calcutta): 126
  Marigold(Loose): 127
  Mashrooms: 128
  Masur Dal: 129
  Masuri: 130
  Medium: 131
  Medium Fine: 132
  Medium Green: 133
  Methi: 134
  Milbar: 135
  Millets: 136
  Mint(Pudina): 137
  Mosambi-Organic: 138
  Mousambi: 139
  Mustard: 140
  Mysore: 141
  NO 1: 142
  NO 2: 143
  Nasik: 144
  Nendra Bale: 145
  Onion: 146
  Onion Green: 147
  Orange: 148
  Other: 149
  Paddy: 150
  Palayamthodan: 151
  Papaya: 152
  Papaya (Raw): 153
  Pea: 154
  Pears: 155
  Peas Wet: 156
  Peas cod: 157
  Peas(Dry): 158
  Pigs: 159
  Pine Apple: 160

In [89]:
# Display mappings for requested categories with fallback column names
if "mappings" not in globals() or len(mappings) == 0:
    print("Mappings not found. Run the encoding cell first.")
else:
    # Requested labels mapped to possible dataset column names
    requested = {
        "State": ["State"],
        "City": ["City", "District", "Market"],
        "Crop": ["Crop", "Crops", "Commodity"],
        "Season": ["Season", "Arrival_Season"],
    }

    shown = []

    for label, candidates in requested.items():
        matched = [c for c in candidates if c in mappings]

        if len(matched) == 0:
            print(f"{label}: not present in dataset")
            print()
            continue

        for col in matched:
            shown.append(col)
            print(f"Mapping for {label} (column: {col}):")
            for value, idx in mappings[col].items():
                print(f"  {value}: {idx}")
            print()

    # Print remaining mapping columns as other details
    remaining_cols = [col for col in mappings.keys() if col not in shown]
    if len(remaining_cols) > 0:
        print("Other mapping details:")
        print()
        for col in remaining_cols:
            print(f"Mapping for {col}:")
            for value, idx in mappings[col].items():
                print(f"  {value}: {idx}")
            print()

Mapping for State (column: State):
  Andhra Pradesh: 0
  Assam: 1
  Bihar: 2
  Chandigarh: 3
  Gujarat: 4
  Haryana: 5
  Himachal Pradesh: 6
  Kerala: 7
  Madhya Pradesh: 8
  Nagaland: 9
  Odisha: 10
  Punjab: 11
  Rajasthan: 12
  Tamil Nadu: 13
  Telangana: 14
  Tripura: 15
  Uttar Pradesh: 16
  Uttarakhand: 17
  West Bengal: 18

Mapping for City (column: City):
  Adilabad: 0
  Ahmedabad: 1
  Ajmer: 2
  Alappuzha: 3
  Aligarh: 4
  Alwar: 5
  Amreli: 6
  Amritsar: 7
  Annamayya: 8
  Ariyalur: 9
  Badaun: 10
  Badwani: 11
  Bahraich: 12
  Balrampur: 13
  Bargarh: 14
  Beawar: 15
  Bhadradri Kothagudem: 16
  Bhatinda: 17
  Bhiwani: 18
  Bikaner: 19
  Birbhum: 20
  Boudh: 21
  Chamba: 22
  Chandigarh: 23
  Chengalpattu: 24
  Chhota Udaipur: 25
  Chittor: 26
  Chittorgarh: 27
  Churu: 28
  Coimbatore: 29
  Coochbehar: 30
  Cuddalore: 31
  Cuttack: 32
  Darjeeling: 33
  Deeg: 34
  Dehradoon: 35
  Dhar: 36
  Dharmapuri: 37
  Dhenkanal: 38
  East Champaran/ Motihari: 39
  East Godavari: 40
  Ernakulam: 41
  Erode: 42
  Etah: 43
  Faridabad: 44
  Faridkot: 45
  Farukhabad: 46
  Fatehpur: 47
  Fazilka: 48
  Ferozpur: 49
  Ganganagar: 50
  Ghazipur: 51
  Gir Somnath: 52
  Gomati: 53
  Gurgaon: 54
  Hamirpur: 55
  Hanumangarh: 56
  Haridwar: 57
  Hathras: 58
  Hissar: 59
  Hoshiarpur: 60
  Idukki: 61
  Jabalpur: 62
  Jagatsinghpur: 63
  Jalandhar: 64
  Jalaun (Orai): 65
  Jalore: 66
  Jhajar: 67
  Jhargram: 68
  Jharsuguda: 69
  Jhunjhunu: 70
  Jodhpur: 71
  Junagarh: 72
  Kaithal: 73
  Kalahandi: 74
  Kallakuruchi: 75
  Kancheepuram: 76
  Kangra: 77
  Kannur: 78
  Karimnagar: 79
  Karur: 80
  Kaushambi: 81
  Khammam: 82
  Khandwa: 83
  Khiri (Lakhimpur): 84
  Khowai: 85
  Kohima: 86
  Kota: 87
  Kottayam: 88
  Kozhikode(Calicut): 89
  Krishnagiri: 90
  Kullu: 91
  Kurukshetra: 92
  Ludhiana: 93
  Madurai: 94
  Maharajganj: 95
  Mahbubnagar: 96
  Mahendragarh-Narnaul: 97
  Malappuram: 98
  Malda: 99
  Mandi: 100
  Mau(Maunathbhanjan): 101
  Mayurbhanja: 102
  Medinipur(E): 103
  Mehsana: 104
  Mewat: 105
  Moga: 106
  Mohali: 107
  Muktsar: 108
  Murshidabad: 109
  Nagaon: 110
  Nagapattinam: 111
  Nagercoil (Kannyiakumari): 112
  Nalgonda: 113
  Namakkal: 114
  Nanital: 115
  Narmada: 116
  Nellore: 117
  Palakad: 118
  Pali: 119
  Palnadu: 120
  Panchkula: 121
  Panipat: 122
  Pathanamthitta: 123
  Perambalur: 124
  Pudukkottai: 125
  Raebarelli: 126
  Rajkot: 127
  Rajsamand: 128
  Ramanathapuram: 129
  Ranipet: 130
  Rayagada: 131
  Rewa: 132
  Rewari: 133
  Rohtak: 134
  Rohtas: 135
  Ropar (Rupnagar): 136
  Sabarkantha: 137
  Sagar: 138
  Saharanpur: 139
  Salem: 140
  Sambalpur: 141
  Sambhal: 142
  Sangrur: 143
  Sant Kabir Nagar: 144
  Sepahijala: 145
  Shamli: 146
  Sheopur: 147
  Sirmore: 148
  Sirsa: 149
  Sitapur: 150
  Sivaganga: 151
  Solan: 152
  Sonipat: 153
  South Tripura: 154
  Sundergarh: 155
  Surat: 156
  Tarntaran: 157
  Thanjavur: 158
  The Nilgiris: 159
  Theni: 160
  Thirssur: 161
  Thiruchirappalli: 162
  Thirunelveli: 163
  Thirupathur: 164
  Thirupur: 165
  Thiruvananthapuram: 166
  Thiruvannamalai: 167
  Thiruvarur: 168
  Thiruvellore: 169
  Tuticorin: 170
  Udhamsinghnagar: 171
  Una: 172
  Vadodara(Baroda): 173
  Valsad: 174
  Vellore: 175
  Villupuram: 176
  Virudhunagar: 177
  Warangal: 178
  Wayanad: 179
  West Godavari: 180
  Yamuna Nagar: 181

Mapping for City (column: District):
  Adilabad: 0
  Ahmedabad: 1
  Ajmer: 2
  Alappuzha: 3
  Aligarh: 4
  Alwar: 5
  Amreli: 6
  Amritsar: 7
  Annamayya: 8
  Ariyalur: 9
  Badaun: 10
  Badwani: 11
  Bahraich: 12
  Balrampur: 13
  Bargarh: 14
  Beawar: 15
  Bhadradri Kothagudem: 16
  Bhatinda: 17
  Bhiwani: 18
  Bikaner: 19
  Birbhum: 20
  Boudh: 21
  Chamba: 22
  Chandigarh: 23
  Chengalpattu: 24
  Chhota Udaipur: 25
  Chittor: 26
  Chittorgarh: 27
  Churu: 28
  Coimbatore: 29
  Coochbehar: 30
  Cuddalore: 31
  Cuttack: 32
  Darjeeling: 33
  Deeg: 34
  Dehradoon: 35
  Dhar: 36
  Dharmapuri: 37
  Dhenkanal: 38
  East Champaran/ Motihari: 39
  East Godavari: 40
  Ernakulam: 41
  Erode: 42
  Etah: 43
  Faridabad: 44
  Faridkot: 45
  Farukhabad: 46
  Fatehpur: 47
  Fazilka: 48
  Ferozpur: 49
  Ganganagar: 50
  Ghazipur: 51
  Gir Somnath: 52
  Gomati: 53
  Gurgaon: 54
  Hamirpur: 55
  Hanumangarh: 56
  Haridwar: 57
  Hathras: 58
  Hissar: 59
  Hoshiarpur: 60
  Idukki: 61
  Jabalpur: 62
  Jagatsinghpur: 63
  Jalandhar: 64
  Jalaun (Orai): 65
  Jalore: 66
  Jhajar: 67
  Jhargram: 68
  Jharsuguda: 69
  Jhunjhunu: 70
  Jodhpur: 71
  Junagarh: 72
  Kaithal: 73
  Kalahandi: 74
  Kallakuruchi: 75
  Kancheepuram: 76
  Kangra: 77
  Kannur: 78
  Karimnagar: 79
  Karur: 80
  Kaushambi: 81
  Khammam: 82
  Khandwa: 83
  Khiri (Lakhimpur): 84
  Khowai: 85
  Kohima: 86
  Kota: 87
  Kottayam: 88
  Kozhikode(Calicut): 89
  Krishnagiri: 90
  Kullu: 91
  Kurukshetra: 92
  Ludhiana: 93
  Madurai: 94
  Maharajganj: 95
  Mahbubnagar: 96
  Mahendragarh-Narnaul: 97
  Malappuram: 98
  Malda: 99
  Mandi: 100
  Mau(Maunathbhanjan): 101
  Mayurbhanja: 102
  Medinipur(E): 103
  Mehsana: 104
  Mewat: 105
  Moga: 106
  Mohali: 107
  Muktsar: 108
  Murshidabad: 109
  Nagaon: 110
  Nagapattinam: 111
  Nagercoil (Kannyiakumari): 112
  Nalgonda: 113
  Namakkal: 114
  Nanital: 115
  Narmada: 116
  Nellore: 117
  Palakad: 118
  Pali: 119
  Palnadu: 120
  Panchkula: 121
  Panipat: 122
  Pathanamthitta: 123
  Perambalur: 124
  Pudukkottai: 125
  Raebarelli: 126
  Rajkot: 127
  Rajsamand: 128
  Ramanathapuram: 129
  Ranipet: 130
  Rayagada: 131
  Rewa: 132
  Rewari: 133
  Rohtak: 134
  Rohtas: 135
  Ropar (Rupnagar): 136
  Sabarkantha: 137
  Sagar: 138
  Saharanpur: 139
  Salem: 140
  Sambalpur: 141
  Sambhal: 142
  Sangrur: 143
  Sant Kabir Nagar: 144
  Sepahijala: 145
  Shamli: 146
  Sheopur: 147
  Sirmore: 148
  Sirsa: 149
  Sitapur: 150
  Sivaganga: 151
  Solan: 152
  Sonipat: 153
  South Tripura: 154
  Sundergarh: 155
  Surat: 156
  Tarntaran: 157
  Thanjavur: 158
  The Nilgiris: 159
  Theni: 160
  Thirssur: 161
  Thiruchirappalli: 162
  Thirunelveli: 163
  Thirupathur: 164
  Thirupur: 165
  Thiruvananthapuram: 166
  Thiruvannamalai: 167
  Thiruvarur: 168
  Thiruvellore: 169
  Tuticorin: 170
  Udhamsinghnagar: 171
  Una: 172
  Vadodara(Baroda): 173
  Valsad: 174
  Vellore: 175
  Villupuram: 176
  Virudhunagar: 177
  Warangal: 178
  Wayanad: 179
  West Godavari: 180
  Yamuna Nagar: 181

Mapping for City (column: Market):
  AJattihalli(Uzhavar Sandhai ) APMC: 0
  APMCKHEDBRAHMA: 1
  Adilabad APMC: 2
  Ahmedgarh APMC: 3
  Ait APMC: 4
  Alangudi(Uzhavar Sandhai ) APMC: 5
  Ambagan APMC: 6
  Ambasamudram(Uzhavar Sandhai ) APMC: 7
  Ammapet(Uzhavar Sandhai ) APMC: 8
  Anandnagar APMC: 9
  Andipatti(Uzhavar Sandhai ) APMC: 10
  Angadippuram VFPCK APMC: 11
  Angamaly APMC: 12
  Anna nagar(Uzhavar Sandhai ) APMC: 13
  Aralamoodu APMC: 14
  Arani(Uzhavar Sandhai ) APMC: 15
  Aranthangi(Uzhavar Sandhai ) APMC: 16
  Arcot(Uzhavar Sandhai ) APMC: 17
  Ariyalur(Uzhavar Sandhai) APMC: 18
  Aruppukottai(Uzhavar Sandhai ) APMC: 19
  Athirampuzha APMC: 20
  Attabira APMC: 21
  Attayampatti(Uzhavar Sandhai ) APMC: 22
  Avallapalli(Uzhavar Sandhai ) APMC: 23
  Avalurpet APMC: 24
  Awagarh APMC: 25
  Babain APMC: 26
  Babrala APMC: 27
  Bachranwa APMC: 28
  Bagasara APMC: 29
  Baghapurana APMC: 30
  Ballabhgarh APMC: 31
  Banki APMC: 32
  Barwala APMC: 33
  Barwala(Hisar) APMC: 34
  Betnoti APMC: 35
  Bharwari APMC: 36
  Bhehjoi APMC: 37
  Bhesan APMC: 38
  Bhiwani APMC: 39
  Bhogpur APMC: 40
  Bhucho APMC: 41
  Bijaynagar APMC: 42
  Bikaner (Grain) APMC: 43
  Birbhum APMC: 44
  Bisoli APMC: 45
  Bodeliu APMC: 46
  Bodinayakanur(Uzhavar Sandhai ) APMC: 47
  Bolpur APMC: 48
  Bonai APMC: 49
  Boudh APMC: 50
  Chakia APMC: 51
  Chala APMC: 52
  Chandigarh(Grain/Fruit) APMC: 53
  Charra APMC: 54
  Chengalpet(Uzhavar Sandhai ) APMC: 55
  Chengannur APMC: 56
  Cherthala APMC: 57
  Cheyyar(Uzhavar Sandhai ) APMC: 58
  Chhachrauli APMC: 59
  Chidambaram(Uzhavar Sandhai ) APMC: 60
  Chikli(Khorgam) APMC: 61
  Chinnamanur(Uzhavar Sandhai ) APMC: 62
  Chittoor APMC: 63
  Chokkikulam(Uzhavar Sandhai ) APMC: 64
  Churu APMC: 65
  Cuddalore(Uzhavar Sandhai ) APMC: 66
  Dammapet APMC: 67
  Darjeeling APMC: 68
  Denduluru APMC: 69
  Denkanikottai(Uzhavar Sandhai ) APMC: 70
  Devakottai (Uzhavar Sandhai ) APMC: 71
  Devarakonda APMC: 72
  Devaram(Uzhavar Sandhai ) APMC: 73
  Dhand APMC: 74
  Dharapuram(Uzhavar Sandhai ) APMC: 75
  Dharmapuri(Uzhavar Sandhai ) APMC: 76
  Dhing APMC: 77
  Dholka APMC: 78
  Dhoraji APMC: 79
  Doomdumia APMC: 80
  Doraha APMC: 81
  Edackattuvayal  VFPCK APMC: 82
  Edapadi (Uzhavar Sandhai ) APMC: 83
  Elamkulam VFPCK APMC: 84
  Elampillai(Uzhavar Sandhai ) APMC: 85
  Farukh Nagar APMC: 86
  Fazilka APMC: 87
  FerozpurZirkha(Nagina) APMC: 88
  Gandarvakottai(Uzhavar Sandhai ) APMC: 89
  Gandhigramam(Uzhavar Sandhai): 90
  Gangoh APMC: 91
  Garh Shankar APMC: 92
  GarhShankar (Kotfatuhi) APMC: 93
  Garhakota APMC: 94
  Gingee(Uzhavar Sandhai ) APMC: 95
  Gobichettipalayam(Uzhavar Sandhai ) APMC: 96
  Gohana APMC: 97
  Goluwala APMC: 98
  Gondal(Veg.market Gondal) APMC: 99
  Govindgarh APMC: 100
  Gudalur(Uzhavar Sandhai ) APMC: 101
  Gudiyatham(Uzhavar Sandhai ) APMC: 102
  Guduvancheri(Uzhavar Sandhai ) APMC: 103
  Gummidipoondy APMC: 104
  Gunpur APMC: 105
  Gurazala APMC: 106
  Gurgaon APMC: 107
  Hadad     APMC: 108
  Haibargaon APMC: 109
  Haldwani APMC: 110
  Hansi APMC: 111
  Hanumana(F&V) APMC: 112
  Hargaon (Laharpur) APMC: 113
  Haridwar Union APMC: 114
  Harsood APMC: 115
  Harur(Uzhavar Sandhai ) APMC: 116
  Hasthampatti(Uzhavar Sandhai ) APMC: 117
  Hosur(Uzhavar Sandhai ) APMC: 118
  Huzzurabad APMC: 119
  Jabalpur APMC: 120
  Jalagandapuram(Uzhavar Sandhai ) APMC: 121
  Jalalabad APMC: 122
  Jalaun APMC: 123
  Jalore APMC: 124
  Jamanian APMC: 125
  Jasdan(Vichhiya) APMC: 126
  Jetpur(Dist.Rajkot) APMC: 127
  Jhajjar APMC: 128
  Jhargram APMC: 129
  Jharsuguda APMC: 130
  Jiaganj APMC: 131
  Jodhpur (F&V) APMC: 132
  Junagarh APMC: 133
  Kadukutty VFPCK APMC: 134
  Kahithapattarai(Uzhavar Sandhai ) APMC: 135
  Kairana APMC: 136
  Kalediya APMC: 137
  Kalikiri APMC: 138
  Kallachi APMC: 139
  Kallakurichi(Uzhavar Sandhai ) APMC: 140
  Kamakhyanagar APMC: 141
  Kambam(Uzhavar Sandhai ) APMC: 142
  Kamlaganj APMC: 143
  Kamuthi(Uzhavar Sandhai ) APMC: 144
  Kandiyaperi(Uzhavar Sandhai ) APMC: 145
  Kangayam(Uzhavar Sandhai ) APMC: 146
  Kannur APMC: 147
  Kapasan APMC: 148
  Karaikudi(Uzhavar Sandhai ) APMC: 149
  Karalam VFPCK APMC: 150
  Karimangalam(Uzhavar Sandhai): 151
  Kariyapatti(Uzhavar Sandhai ) APMC: 152
  Karsiyang(Matigara) APMC: 153
  Karur(Uzhavar Sandhai ) APMC: 154
  Kattakada APMC: 155
  Kattampak  VFPCK APMC: 156
  Kattappana APMC: 157
  Khalilabad APMC: 158
  Kicchha APMC: 159
  Kishunpur APMC: 160
  Kohima APMC: 161
  Kolaghat APMC: 162
  Konch APMC: 163
  Kopaganj APMC: 164
  Kosli APMC: 165
  Kota APMC: 166
  Kotkapura APMC: 167
  Kottakkal APMC: 168
  Kovilnada  VFPCK APMC: 169
  Kovilpatti(Uzhavar Sandhai ) APMC: 170
  Krishnagiri(Uzhavar Sandhai ) APMC: 171
  Kulithalai(Uzhavar Sandhai ) APMC: 172
  Kumarapalayam(Uzhavar Sandhai ) APMC: 173
  Kumbakonam (Uzhavar Sandhai ) APMC: 174
  Kundrathur(Uzhavar Sandhai ) APMC: 175
  Kurali APMC: 176
  Kurichi(Uzhavar Sandhai ) APMC: 177
  Lalganj APMC: 178
  Lalgudi(Uzhavar Sandhai ) APMC: 179
  Lalru APMC: 180
  Ludhiana APMC: 181
  Madanapalli APMC: 182
  Madanganj Kishangarh APMC: 183
  Madhuranthagam(Uzhavar Sandhai ) APMC: 184
  Maigalganj APMC: 185
  Manachanallur(Uzhavar Sandhai ) APMC: 186
  Manapparai(Uzhavar Sandhai ) APMC: 187
  Manglaur APMC: 188
  Mankada VFPCK APMC: 189
  Mannar APMC: 190
  Mannargudi I(Uzhavar Sandhai ) APMC: 191
  Mannargudi II(Uzhavar Sandhai ) APMC: 192
  Manubazar: 193
  Marottichal  VFPCK APMC: 194
  Mathabhanga APMC: 195
  Mayiladuthurai(Uzhavar Sandhai ) APMC: 196
  Mecheri(Uzhavar Sandhai): 197
  Meghraj APMC: 198
  Meham APMC: 199
  Mehatpur APMC: 200
  Mehsana(Jornang) APMC: 201
  Melaghar APMC: 202
  Melapalayam(Uzhavar Sandhai ) APMC: 203
  Melur(Uzhavar Sandhai ) APMC: 204
  Mettupalayam(Uzhavar Sandhai ) APMC: 205
  Mettur(Uzhavar Sandhai ) APMC: 206
  Modasar APMC: 207
  Moga APMC: 208
  Mohanur(Uzhavar Sandhai ) APMC: 209
  Morinda APMC: 210
  Muktsar APMC: 211
  Musiri(Uzhavar Sandhai ) APMC: 212
  NGO Colony(Uzhavar Sandhai ) APMC: 213
  Naanpara APMC: 214
  Nagapattinam(Uzhavar Sandhai ) APMC: 215
  Namakkal(Uzhavar Sandhai ) APMC: 216
  Nanakmatta APMC: 217
  Narasinghpur APMC: 218
  Narnaul APMC: 219
  Natrampalli(Uzhavar Sandhai ) APMC: 220
  Natwar APMC: 221
  Needamangalam(Uzhavar Sandhai ) APMC: 222
  Nizar(Kukarmuda) APMC: 223
  Nuguru Charla APMC: 224
  Nutanbazar APMC: 225
  PMY Chamba: 226
  PMY Hamirpur: 227
  PMY Kangra: 228
  PMY Kather Solan: 229
  PMY Paonta Sahib: 230
  Padra APMC: 231
  Pala APMC: 232
  Palacode(Uzhavar Sandhai ) APMC: 233
  Palanganatham(Uzhavar Sandhai ) APMC: 234
  Palayam APMC: 235
  Palayamkottai(Uzhavar Sandhai ) APMC: 236
  Palladam(Uzhavar Sandhai ) APMC: 237
  Pallapatti (Uzhavar Sandhai ) APMC: 238
  Pallavaram(Uzhavar Sandhai ) APMC: 239
  Pallikkal  VFPCK APMC: 240
  Pallikkal VFPCK APMC: 241
  Pampady APMC: 242
  Panchpedwa APMC: 243
  Panipat APMC: 244
  Pappanchani VFPCK APMC: 245
  Paramakudi(Uzhavar Sandhai ) APMC: 246
  Paramathivelur(Uzhavar Sandhai ) APMC: 247
  Pataudi APMC: 248
  Pattambi APMC: 249
  Patti APMC: 250
  Pattukottai(Uzhavar Sandhai ) APMC: 251
  Payyannur APMC: 252
  Pennagaram(Uzhavar Sandhai ) APMC: 253
  Perambalur(Uzhavar Sandhai ) APMC: 254
  Perampet(Uzhavar Sandhai): 255
  Periyakulam(Uzhavar Sandhai ) APMC: 256
  Periyar Nagar(Uzhavar Sandhai ) APMC: 257
  Perumbavoor APMC: 258
  Perundurai(Uzhavar Sandhai ) APMC: 259
  Phillaur(Apra Mandi) APMC: 260
  Pipli APMC: 261
  Pollachi(Uzhavar Sandhai ) APMC: 262
  Polur(Uzhavar Sandhai ) APMC: 263
  Ponnamaravathi(Uzhavar Sandhai): 264
  Pudukottai(Uzhavar Sandhai ) APMC: 265
  Pulpally APMC: 266
  Punganur APMC: 267
  Quilandy APMC: 268
  RSPuram(Uzhavar Sandhai ) APMC: 269
  Rahama APMC: 270
  Rairakhol APMC: 271
  Rairangpur APMC: 272
  Rajgarh APMC: 273
  Rajkot(Veg.Sub Yard) APMC: 274
  Rajpipla APMC: 275
  Rajsamand APMC: 276
  Ramanathapuram(Uzhavar Sandhai ) APMC: 277
  Ranipettai(Uzhavar Sandhai ) APMC: 278
  Rasipuram(Uzhavar Sandhai ) APMC: 279
  Ravulapelem APMC: 280
  Rawatsar APMC: 281
  Rayagada APMC: 282
  Rayya APMC: 283
  Rewari APMC: 284
  Rohtak APMC: 285
  Roorkee APMC: 286
  Rudrapur APMC: 287
  SMY Baijnath: 288
  SMY Bhuntar: 289
  SMY Dharamshala: 290
  SMY Jaisinghpur: 291
  SMY Nadaun: 292
  SMY Nahan: 293
  SMY Nalagarh: 294
  SMY Palampur: 295
  SMY Santoshgarh: 296
  SMY Takoli: 297
  Sadhaura APMC: 298
  Sahnewal APMC: 299
  Salon APMC: 300
  Samalkha APMC: 301
  Sampath Nagar(Uzhavar Sandhai ) APMC: 302
  Samsi APMC: 303
  Sangriya APMC: 304
  Sankarapuram(Uzhavar Sandhai ) APMC: 305
  Sargipali APMC: 306
  Sarvepalli APMC: 307
  Sathiyamagalam(Uzhavar Sandhai ) APMC: 308
  Sathupally APMC: 309
  Sendhwa(F&V) APMC: 310
  Shadabad APMC: 311
  Sheopurkalan APMC: 312
  Sikri APMC: 313
  Siliguri APMC: 314
  Singampunari(Uzhavar Sandhai ) APMC: 315
  Singanallur(Uzhavar Sandhai ) APMC: 316
  Sirkali(Uzhavar Sandhai ) APMC: 317
  Sitarganj APMC: 318
  Sivakasi(Uzhavar Sandhai ) APMC: 319
  Sohna APMC: 320
  Sojat City APMC: 321
  Songadh APMC: 322
  Songadh(Badarpada) APMC: 323
  Songadh(Umrada) APMC: 324
  Sooramangalam(Uzhavar Sandhai ) APMC: 325
  Sridungargarh APMC: 326
  Sriganganagar (F&V) APMC: 327
  Sulur(Uzhavar Sandhai ) APMC: 328
  Sundarapuram(Uzhavar Sandhai ) APMC: 329
  Surajgarh APMC: 330
  Surat APMC: 331
  Taliparamba APMC: 332
  Tamarainagar(Uzhavar Sandhai ) APMC: 333
  Tamluk (Medinipur E) APMC: 334
  Tauru APMC: 335
  Teliamura APMC: 336
  Thalasserry APMC: 337
  Thalavaipuram(Uzhavar Sandhai ) APMC: 338
  Thalayolaparambu APMC: 339
  Thammampatti (Uzhavar Sandhai ) APMC: 340
  Thathakapatti(Uzhavar Sandhai ) APMC: 341
  Thengamam VFPCK APMC: 342
  Theni(Uzhavar Sandhai ) APMC: 343
  Thirukalukundram(Uzhavar Sandhai ) APMC: 344
  Thirumangalam(Uzhavar Sandhai ) APMC: 345
  Thirupathur APMC: 346
  Thiruvali  VFPCK APMC: 347
  Thottippal VFPCK APMC: 348
  Thrippunithura APMC: 349
  Thuraiyur APMC: 350
  Tindivanam APMC: 351
  Tiruchengode APMC: 352
  Tirupatthur(Uzhavar Sandhai ) APMC: 353
  Tiruppur (North) (Uzhavar Sandhai ) APMC: 354
  Tiruppur (South) (Uzhavar Sandhai ) APMC: 355
  Tiruthani(Uzhavar Sandhai ) APMC: 356
  Tiruthuraipoondi(Uzhavar Sandhai ) APMC: 357
  Tiruvannamalai(Uzhavar Sandhai ) APMC: 358
  Tiruvarur(Uzhavar Sandhai ) APMC: 359
  Udhagamandalam(Uzhavar Sandhai ) APMC: 360
  Udumalpet APMC: 361
  Ulundurpettai APMC: 362
  Usilampatti(Uzhavar Sandhai ) APMC: 363
  Vadakkenchery APMC: 364
  Vadalur(Uzhavar Sandhai ) APMC: 365
  Vadaseri APMC: 366
  Vadavalli(Uzhavar Sandhai ) APMC: 367
  Valangaiman APMC: 368
  Valmikipuram APMC: 369
  Vandavasi(Uzhavar Sandhai ) APMC: 370
  Vaniyamkulam  VFPCK APMC: 371
  Vaniyampadi(Uzhavar Sandhai ) APMC: 372
  Vazhapadi(Uzhavar Sandhai): 373
  Velayuthampalayam(Uzhavar Sandhai ) APMC: 374
  Vengamedu(Uzhavar Sandhai ) APMC: 375
  Vengola  VFPCK APMC: 376
  Veraval APMC: 377
  Vijaypur APMC: 378
  Vikasnagar APMC: 379
  Viralimalai(Uzhavar Sandhai ) APMC: 380
  Virudhunagar(Uzhavar Sandhai ) APMC: 381
  Viruthachalam(Uzhavar Sandhai ) APMC: 382
  Warangal APMC: 383
  Zira APMC: 384
  kalanwali APMC: 385

Mapping for Crop (column: Commodity):
  Amaranthus: 0
  Amla(Nelli Kai): 1
  Amranthas Red: 2
  Apple: 3
  Arecanut(Betelnut/Supari): 4
  Arhar Dal(Tur Dal): 5
  Arhar(Tur/Red Gram)(Whole): 6
  Ashgourd: 7
  Bajra(Pearl Millet/Cumbu): 8
  Banana: 9
  Banana - Green: 10
  Barley(Jau): 11
  Beans: 12
  Beetroot: 13
  Bengal Gram(Gram)(Whole): 14
  Ber(Zizyphus/Borehannu): 15
  Betal Leaves: 16
  Bhindi(Ladies Finger): 17
  Bitter gourd: 18
  Black Gram Dal(Urd Dal): 19
  Black Gram(Urd Beans)(Whole): 20
  Black pepper: 21
  Bottle gourd: 22
  Brinjal: 23
  Cabbage: 24
  Capsicum: 25
  Cardamoms: 26
  Carrot: 27
  Cashewnuts: 28
  Castor Seed: 29
  Cauliflower: 30
  Chikoos(Sapota): 31
  Chili Red: 32
  Chow Chow: 33
  Cluster beans: 34
  Coconut: 35
  Coconut Oil: 36
  Coconut Seed: 37
  Coffee: 38
  Colacasia: 39
  Copra: 40
  Coriander(Leaves): 41
  Corriander seed: 42
  Cotton: 43
  Cowpea(Veg): 44
  Cucumbar(Kheera): 45
  Custard Apple(Sharifa): 46
  Drumstick: 47
  Elephant Yam(Suran)/Amorphophallus: 48
  Field Pea: 49
  Fig(Anjura/Anjeer): 50
  Firewood: 51
  Fish: 52
  French Beans(Frasbean): 53
  Galgal(Lemon): 54
  Garlic: 55
  Ginger(Dry): 56
  Ginger(Green): 57
  Goat: 58
  Gram Raw(Chholia): 59
  Grapes: 60
  Green Avare(W): 61
  Green Chilli: 62
  Green Gram Dal(Moong Dal): 63
  Green Gram(Moong)(Whole): 64
  Green Peas: 65
  Groundnut: 66
  Guar: 67
  Guava: 68
  Gur(Jaggery): 69
  Indian Beans(Seam): 70
  Indian Colza(Sarson): 71
  Jack Fruit(Ripe): 72
  Jasmine: 73
  Jute: 74
  Kakada: 75
  Karbuja(Musk Melon): 76
  Kinnow: 77
  Kiwi Fruit: 78
  Knool Khol: 79
  Leafy Vegetable: 80
  Lemon: 81
  Lime: 82
  Little gourd(Kundru): 83
  Long Melon(Kakri): 84
  Mahedi: 85
  Maize: 86
  Mango: 87
  Mango(Raw-Ripe): 88
  Marigold(Calcutta): 89
  Marigold(loose): 90
  Mashrooms: 91
  Masur Dal: 92
  Methi Seeds: 93
  Methi(Leaves): 94
  Millets: 95
  Mint(Pudina): 96
  Mousambi(Sweet Lime): 97
  Mustard: 98
  Onion: 99
  Onion Green: 100
  Orange: 101
  Paddy(Basmati): 102
  Paddy(Common): 103
  Papaya: 104
  Papaya(Raw): 105
  Pea Pod/Pea Cod/हरी मटर: 106
  Pear(Marasebu): 107
  Peas Wet: 108
  Peas(Dry): 109
  Pegeon Pea(Arhar Fali): 110
  Pigs: 111
  Pineapple: 112
  Pointed gourd(Parval): 113
  Pomegranate: 114
  Potato: 115
  Pumpkin: 116
  Raddish: 117
  Rat Tail Radish(Mogari): 118
  Rice: 119
  Ridgeguard(Tori): 120
  Rose(Local): 121
  Round gourd: 122
  Rubber: 123
  Season Leaves: 124
  Snakeguard: 125
  Soyabean: 126
  Spinach: 127
  Sponge gourd: 128
  Squash(Chappal Kadoo): 129
  Strawberry: 130

In [90]:
object_cols

Index(['State', 'District', 'Market', 'Commodity', 'Variety', 'Grade',
       'Arrival_Date', 'City', 'Crop Type', 'Season'],
      dtype='object')

In [91]:
print('df columns:', list(df.columns))
print('mapping keys:', list(mappings.keys()) if 'mappings' in globals() else [])

for token in ['state', 'city', 'district', 'market', 'crop', 'commodity', 'season']:
    cols = [c for c in (list(mappings.keys()) if 'mappings' in globals() else []) if token in c.lower()]
    print(f"{token} ->", cols)

df columns: ['State', 'District', 'Market', 'Commodity', 'Variety', 'Grade', 'Arrival_Date', 'Min_x0020_Price', 'Max_x0020_Price', 'Modal_x0020_Price', 'City', 'Crop Type', 'Season', 'Temperature (degree C)', 'Rainfall (mm)', 'Supply Volume (tons)', 'Demand Volume (tons)', 'Transportation Cost (₹/ton)', 'Fertilizer Usage (kg/hectare)', 'Pest Infestation (0-1)', 'Market Competition (0-1)', 'Price (₹/ton)']
mapping keys: ['State', 'District', 'Market', 'Commodity', 'Variety', 'Grade', 'Arrival_Date', 'City', 'Crop Type', 'Season']
state -> ['State']
city -> ['City']
district -> ['District']
market -> ['Market']
crop -> ['Crop Type']
commodity -> ['Commodity']
season -> ['Season']

In [92]:
df.head()

   State  District  ...  Market Competition (0-1)  Price (₹/ton)
0     12        71  ...                     0.127           8000
1     12        71  ...                     0.544           1000
2     12        71  ...                     0.181           6000
3     12        71  ...                     0.419           7000
4     12        15  ...                     0.706           5300

[5 rows x 22 columns]

In [93]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7611 entries, 0 to 7610
Data columns (total 22 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   State                          7611 non-null   int64
 1   District                       7611 non-null   int64
 2   Market                         7611 non-null   int64
 3   Commodity                      7611 non-null   int64
 4   Variety                        7611 non-null   int64
 5   Grade                          7611 non-null   int64
 6   Arrival_Date                   7611 non-null   int64
 7   Min_x0020_Price                7611 non-null   int64
 8   Max_x0020_Price                7611 non-null   int64
 9   Modal_x0020_Price              7611 non-null   int64
 10  City                           7611 non-null   int64
 11  Crop Type                      7611 non-null   int64
 12  Season                         7611 non-null   int64
 13  Temperature (degree C)         7611 non-null   float64
 14  Rainfall (mm)                  7611 non-null   float64
 15  Supply Volume (tons)           7611 non-null   float64
 16  Demand Volume (tons)           7611 non-null   float64
 17  Transportation Cost (₹/ton)    7611 non-null   float64
 18  Fertilizer Usage (kg/hectare)  7611 non-null   float64
 19  Pest Infestation (0-1)         7611 non-null   float64
 20  Market Competition (0-1)       7611 non-null   float64
 21  Price (₹/ton)                  7611 non-null   int64
dtypes: float64(8), int64(14)
memory usage: 1.3 MB

In [94]:
# model tarined before normailsation

In [52]:
# Prepare features and target
target_col = "Price (₹/ton)" if "Price (₹/ton)" in df.columns else "Modal_x0020_Price"
X = df.drop(columns=[target_col])
y = df[target_col]

# Split data into training, validation, and testing sets
X_train, X_temp, y_train, y_temp = train_test_split(X, y, test_size=0.4, random_state=42)
X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp, test_size=0.5, random_state=42)

print(f"Target used: {target_col}")
print(f"Train shape: {X_train.shape}, Val shape: {X_val.shape}, Test shape: {X_test.shape}")

Target used: Price (₹/ton)
Train shape: (4566, 21), Val shape: (1522, 21), Test shape: (1523, 21)

In [95]:
df.columns

Index(['State', 'District', 'Market', 'Commodity', 'Variety', 'Grade',
       'Arrival_Date', 'Min_x0020_Price', 'Max_x0020_Price',
       'Modal_x0020_Price', 'City', 'Crop Type', 'Season',
       'Temperature (degree C)', 'Rainfall (mm)', 'Supply Volume (tons)',
       'Demand Volume (tons)', 'Transportation Cost (₹/ton)',
       'Fertilizer Usage (kg/hectare)', 'Pest Infestation (0-1)',
       'Market Competition (0-1)', 'Price (₹/ton)'],
      dtype='object')

In [96]:
# Drop the 'Unnamed: 0' and 'Date' columns
df = df.drop(columns=['Unnamed: 0', 'Date'], errors='ignore')

In [97]:
df.isnull().sum()

State                            0
District                         0
Market                           0
Commodity                        0
Variety                          0
Grade                            0
Arrival_Date                     0
Min_x0020_Price                  0
Max_x0020_Price                  0
Modal_x0020_Price                0
City                             0
Crop Type                        0
Season                           0
Temperature (degree C)           0
Rainfall (mm)                    0
Supply Volume (tons)             0
Demand Volume (tons)             0
Transportation Cost (₹/ton)      0
Fertilizer Usage (kg/hectare)    0
Pest Infestation (0-1)           0
Market Competition (0-1)         0
Price (₹/ton)                    0
dtype: int64

In [56]:
# Initialize and train the XGBoost model
# Encode categorical columns so XGBoost receives numeric inputs only.
X_train_enc = pd.get_dummies(X_train, drop_first=False)
X_val_enc = pd.get_dummies(X_val, drop_first=False).reindex(columns=X_train_enc.columns, fill_value=0)
X_test_enc = pd.get_dummies(X_test, drop_first=False).reindex(columns=X_train_enc.columns, fill_value=0)

model = XGBRegressor(
    objective='reg:squarederror',
    eval_metric='rmse',
    random_state=42,
    n_estimators=300,
    learning_rate=0.05,
    max_depth=6,
)
model.fit(X_train_enc, y_train)

# Make predictions
y_pred_train = model.predict(X_train_enc)
y_pred_val = model.predict(X_val_enc)
y_pred_test = model.predict(X_test_enc)

# Evaluate the model (compatible across sklearn versions)
train_mse = mean_squared_error(y_train, y_pred_train)
val_mse = mean_squared_error(y_val, y_pred_val)
test_mse = mean_squared_error(y_test, y_pred_test)

train_rmse = train_mse ** 0.5
val_rmse = val_mse ** 0.5
test_rmse = test_mse ** 0.5

train_r2 = r2_score(y_train, y_pred_train)
val_r2 = r2_score(y_val, y_pred_val)
test_r2 = r2_score(y_test, y_pred_test)

print(f"Train RMSE: {train_rmse:.2f}, R2: {train_r2:.4f}")
print(f"Val   RMSE: {val_rmse:.2f}, R2: {val_r2:.4f}")
print(f"Test  RMSE: {test_rmse:.2f}, R2: {test_r2:.4f}")

Train RMSE: 22.70, R2: 1.0000
Val   RMSE: 850.72, R2: 0.9691
Test  RMSE: 1393.58, R2: 0.9710

In [57]:
print(f"Train RMSE: {train_rmse:.2f}")
print(f"Validation RMSE: {val_rmse:.2f}")
print(f"Test RMSE: {test_rmse:.2f}")

print(f"Training R^2: {train_r2:.2f}")
print(f"Validation R^2: {val_r2:.2f}")
print(f"Test R^2: {test_r2:.2f}")

Train RMSE: 22.70
Validation RMSE: 850.72
Test RMSE: 1393.58

In [98]:
# data normalisation models are built

In [62]:
# Assume df is your DataFrame
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

# Create a list of input columns to be normalized
input_columns = ['Temperature (degree C)', 'Rainfall (mm)', 'Supply Volume (tons)',
                 'Demand Volume (tons)', 'Transportation Cost (₹/ton)',
                 'Fertilizer Usage (kg/hectare)', 'Pest Infestation (0-1)',
                 'Market Competition (0-1)']

# Initialize the MinMaxScaler
scaler = MinMaxScaler()

# Apply the scaler to the input columns
df[input_columns] = scaler.fit_transform(df[input_columns])

# Now df contains the normalized input columns
print(df.head())

       State District  ... Market Competition (0-1) Price (₹/ton)
0  Rajasthan  Jodhpur  ...                    0.127          8000
1  Rajasthan  Jodhpur  ...                    0.544          1000
2  Rajasthan  Jodhpur  ...                    0.181          6000
3  Rajasthan  Jodhpur  ...                    0.419          7000
4  Rajasthan   Beawar  ...                    0.706          5300

[5 rows x 22 columns]

In [99]:
df.tail()

      State  District  ...  Market Competition (0-1)  Price (₹/ton)
7606      6        77  ...                     0.361           7000
7607      6        77  ...                     0.195          12000
7608      6        77  ...                     0.562           5500
7609      6        77  ...                     0.902          13500
7610      7       166  ...                     0.463           7000

[5 rows x 22 columns]

In [100]:
print(f"Training RMSE: {train_rmse:.2f}")
print(f"Validation RMSE: {val_rmse:.2f}")
print(f"Test RMSE: {test_rmse:.2f}")

print(f"Training R^2: {train_r2:.2f}")
print(f"Validation R^2: {val_r2:.2f}")
print(f"Test R^2: {test_r2:.2f}")

Training RMSE: 1373.50
Validation RMSE: 5446.75
Test RMSE: 8551.50
Training R^2: 0.94
Validation R^2: -0.27
Test R^2: -0.09

In [101]:
# wrapper technique for feature selection

In [71]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.feature_selection import RFE
from sklearn.preprocessing import MinMaxScaler

# Assuming df is your DataFrame

# Define input and output columns
X = df.drop(columns=['Price (₹/ton)'])
y = df['Price (₹/ton)']

# Convert categorical columns to numeric first
X_encoded = pd.get_dummies(X, drop_first=False)

# Normalize the input features
scaler = MinMaxScaler()
X_scaled = scaler.fit_transform(X_encoded)

# Use a subset for faster RFE execution
max_rows = min(2500, X_scaled.shape[0])
X_rfe = X_scaled[:max_rows]
y_rfe = y.iloc[:max_rows]

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_rfe, y_rfe, test_size=0.2, random_state=42)

# Initialize the model
model = LinearRegression()

# Initialize RFE with faster elimination steps
n_features = min(5, X_encoded.shape[1])
rfe = RFE(estimator=model, n_features_to_select=n_features, step=0.2)

# Fit RFE
rfe.fit(X_train, y_train)

# Get the selected features
selected_features = X_encoded.columns[rfe.support_]

print("Selected Features:")
print(selected_features)

Selected Features:
Index(['Min_x0020_Price', 'Max_x0020_Price', 'Modal_x0020_Price',
       'State_Andhra Pradesh', 'State_Chandigarh'],
      dtype='object')

In [72]:
# Manually select the desired input features
selected_features = ['Rainfall (mm)', 'Supply Volume (tons)', 'Demand Volume (tons)',
                     'Transportation Cost (₹/ton)', 'Market Competition (0-1)']

# Prepare features and target using only the selected features
X = df[selected_features]
y = df['Price (₹/ton)']

In [73]:
# Prepare features and target
# X = df.drop(columns=['Price (₹/ton)'])
# y = df['Price (₹/ton)']

# Split the data into training, validation, and test sets
X_train, X_temp, y_train, y_temp = train_test_split(X, y, test_size=0.4, random_state=42)
X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp, test_size=0.5, random_state=42)

In [74]:
# Initialize and train the XGBoost model
model = XGBRegressor(objective='reg:squarederror', eval_metric='rmse')
model.fit(X_train, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric='rmse', feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=None, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=None,
             n_jobs=None, num_parallel_tree=None, ...)

In [75]:
# Initialize and train the XGBoost model
model = XGBRegressor(objective='reg:squarederror', eval_metric='rmse', random_state=42)
model.fit(X_train, y_train)

# Make predictions
y_pred_train = model.predict(X_train)
y_pred_val = model.predict(X_val)
y_pred_test = model.predict(X_test)

# Evaluate the model
train_mse = mean_squared_error(y_train, y_pred_train)
val_mse = mean_squared_error(y_val, y_pred_val)
test_mse = mean_squared_error(y_test, y_pred_test)

train_rmse = train_mse ** 0.5
val_rmse = val_mse ** 0.5
test_rmse = test_mse ** 0.5

train_r2 = r2_score(y_train, y_pred_train)
val_r2 = r2_score(y_val, y_pred_val)
test_r2 = r2_score(y_test, y_pred_test)

In [76]:
print(f"Training RMSE: {train_rmse:.2f}")
print(f"Validation RMSE: {val_rmse:.2f}")
print(f"Test RMSE: {test_rmse:.2f}")

print(f"Training R^2: {train_r2:.2f}")
print(f"Validation R^2: {val_r2:.2f}")
print(f"Test R^2: {test_r2:.2f}")

Training RMSE: 1608.84
Validation RMSE: 5394.40
Test RMSE: 8465.71
Training R^2: 0.92
Validation R^2: -0.24
Test R^2: -0.07

In [102]:
# lasso

In [77]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import Lasso
from sklearn.preprocessing import StandardScaler

# Assuming df is your DataFrame

# Prepare features and target
X = df.drop(columns=['Price (₹/ton)'])
y = df['Price (₹/ton)']

# Convert categorical columns to numeric first
X_encoded = pd.get_dummies(X, drop_first=False)

# Split the data into training, validation, and test sets
X_train, X_temp, y_train, y_temp = train_test_split(X_encoded, y, test_size=0.4, random_state=42)
X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp, test_size=0.5, random_state=42)

# Normalize the features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_val_scaled = scaler.transform(X_val)
X_test_scaled = scaler.transform(X_test)

# Perform Lasso regression for feature selection
lasso = Lasso(alpha=0.1, max_iter=10000)
lasso.fit(X_train_scaled, y_train)

# Get the selected features (non-zero coefficients)
selected_features = X_train.columns[lasso.coef_ != 0]

print("Selected features using Lasso:")
print(selected_features)

Selected features using Lasso:
Index(['Min_x0020_Price', 'Max_x0020_Price', 'Modal_x0020_Price',
       'Temperature (degree C)', 'Rainfall (mm)', 'Demand Volume (tons)',
       'Transportation Cost (₹/ton)', 'Fertilizer Usage (kg/hectare)',
       'Pest Infestation (0-1)', 'Market Competition (0-1)',
       ...
       'Crop Type_Marigold(loose)', 'Crop Type_Onion',
       'Crop Type_Pea Pod/Pea Cod/हरी मटर', 'Crop Type_Peas(Dry)',
       'Crop Type_Pineapple', 'Crop Type_Strawberry',
       'Crop Type_Sweet Pumpkin', 'Crop Type_Taramira', 'Crop Type_Tinda',
       'Crop Type_Tube Rose(Loose)'],
      dtype='object', length=325)

In [78]:
# Manually select the desired input features
selected_features = ['Temperature (degree C)', 'Rainfall (mm)', 'Supply Volume (tons)',
                     'Demand Volume (tons)', 'Transportation Cost (₹/ton)',
                     'Fertilizer Usage (kg/hectare)', 'Pest Infestation (0-1)',
                     'Market Competition (0-1)']

# Prepare features and target using only the selected features
X = df[selected_features]
y = df['Price (₹/ton)']

In [79]:
# Prepare features and target
# X = df.drop(columns=['Price (₹/ton)'])
# y = df['Price (₹/ton)']

# Split the data into training, validation, and test sets
X_train, X_temp, y_train, y_temp = train_test_split(X, y, test_size=0.4, random_state=42)
X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp, test_size=0.5, random_state=42)

In [80]:
# Initialize and train the XGBoost model
model = XGBRegressor(objective='reg:squarederror', eval_metric='rmse', random_state=42)
model.fit(X_train, y_train)

# Make predictions
y_pred_train = model.predict(X_train)
y_pred_val = model.predict(X_val)
y_pred_test = model.predict(X_test)

# Evaluate the model
train_mse = mean_squared_error(y_train, y_pred_train)
val_mse = mean_squared_error(y_val, y_pred_val)
test_mse = mean_squared_error(y_test, y_pred_test)

train_rmse = train_mse ** 0.5
val_rmse = val_mse ** 0.5
test_rmse = test_mse ** 0.5

train_r2 = r2_score(y_train, y_pred_train)
val_r2 = r2_score(y_val, y_pred_val)
test_r2 = r2_score(y_test, y_pred_test)

In [81]:
print(f"Training RMSE: {train_rmse:.2f}")
print(f"Validation RMSE: {val_rmse:.2f}")
print(f"Test RMSE: {test_rmse:.2f}")

print(f"Training R^2: {train_r2:.2f}")
print(f"Validation R^2: {val_r2:.2f}")
print(f"Test R^2: {test_r2:.2f}")

Training RMSE: 1373.50
Validation RMSE: 5446.75
Test RMSE: 8551.50
Training R^2: 0.94
Validation R^2: -0.27
Test R^2: -0.09

In [103]:
import pickle

# Save the trained model to a file using pickle
with open('xgboost_model.pkl', 'wb') as file:
    pickle.dump(model, file)

In [104]:
# Load the model from the file
with open('xgboost_model.pkl', 'rb') as file:
    loaded_model = pickle.load(file)

# Now you can use 'loaded_model' to make predictions

In [82]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score

# Initialize and train the Random Forest Regressor
rf_model = RandomForestRegressor(random_state=42, n_estimators=200)
rf_model.fit(X_train, y_train)

# Make predictions
y_pred_train_rf = rf_model.predict(X_train)
y_pred_val_rf = rf_model.predict(X_val)
y_pred_test_rf = rf_model.predict(X_test)

# Evaluate the model
train_mse_rf = mean_squared_error(y_train, y_pred_train_rf)
val_mse_rf = mean_squared_error(y_val, y_pred_val_rf)
test_mse_rf = mean_squared_error(y_test, y_pred_test_rf)

train_rmse_rf = train_mse_rf ** 0.5
val_rmse_rf = val_mse_rf ** 0.5
test_rmse_rf = test_mse_rf ** 0.5

train_r2_rf = r2_score(y_train, y_pred_train_rf)
val_r2_rf = r2_score(y_val, y_pred_val_rf)
test_r2_rf = r2_score(y_test, y_pred_test_rf)

print(f"Random Forest - Training RMSE: {train_rmse_rf:.2f}")
print(f"Random Forest - Validation RMSE: {val_rmse_rf:.2f}")
print(f"Random Forest - Test RMSE: {test_rmse_rf:.2f}")

print(f"Random Forest - Training R^2: {train_r2_rf:.2f}")
print(f"Random Forest - Validation R^2: {val_r2_rf:.2f}")
print(f"Random Forest - Test R^2: {test_r2_rf:.2f}")

Random Forest - Training RMSE: 2239.00
Random Forest - Validation RMSE: 5134.64
Random Forest - Test RMSE: 8283.41
Random Forest - Training R^2: 0.85
Random Forest - Validation R^2: -0.13
Random Forest - Test R^2: -0.02

In [83]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

# Initialize and train the Linear Regressor
lr_model = LinearRegression()
lr_model.fit(X_train, y_train)

# Make predictions
y_pred_train_lr = lr_model.predict(X_train)
y_pred_val_lr = lr_model.predict(X_val)
y_pred_test_lr = lr_model.predict(X_test)

# Evaluate the model
train_mse_lr = mean_squared_error(y_train, y_pred_train_lr)
val_mse_lr = mean_squared_error(y_val, y_pred_val_lr)
test_mse_lr = mean_squared_error(y_test, y_pred_test_lr)

train_rmse_lr = train_mse_lr ** 0.5
val_rmse_lr = val_mse_lr ** 0.5
test_rmse_lr = test_mse_lr ** 0.5

train_r2_lr = r2_score(y_train, y_pred_train_lr)
val_r2_lr = r2_score(y_val, y_pred_val_lr)
test_r2_lr = r2_score(y_test, y_pred_test_lr)

print(f"Linear Regression - Training RMSE: {train_rmse_lr:.2f}")
print(f"Linear Regression - Validation RMSE: {val_rmse_lr:.2f}")
print(f"Linear Regression - Test RMSE: {test_rmse_lr:.2f}")

print(f"Linear Regression - Training R^2: {train_r2_lr:.2f}")
print(f"Linear Regression - Validation R^2: {val_r2_lr:.2f}")
print(f"Linear Regression - Test R^2: {test_r2_lr:.2f}")

Linear Regression - Training RMSE: 5819.87
Linear Regression - Validation RMSE: 4838.31
Linear Regression - Test RMSE: 8194.14
Linear Regression - Training R^2: 0.00
Linear Regression - Validation R^2: 0.00
Linear Regression - Test R^2: -0.00

In [84]:
from sklearn.svm import SVR
from sklearn.metrics import mean_squared_error, r2_score

# Initialize and train the SVR
svr_model = SVR(C=5.0, epsilon=0.1, kernel='rbf')

# Fit on a subset for faster runtime on large data
subset_size = min(2500, len(X_train))
svr_model.fit(X_train[:subset_size], y_train.iloc[:subset_size])

# Make predictions
y_pred_train_svr = svr_model.predict(X_train)
y_pred_val_svr = svr_model.predict(X_val)
y_pred_test_svr = svr_model.predict(X_test)

# Evaluate the model
train_mse_svr = mean_squared_error(y_train, y_pred_train_svr)
val_mse_svr = mean_squared_error(y_val, y_pred_val_svr)
test_mse_svr = mean_squared_error(y_test, y_pred_test_svr)

train_rmse_svr = train_mse_svr ** 0.5
val_rmse_svr = val_mse_svr ** 0.5
test_rmse_svr = test_mse_svr ** 0.5

train_r2_svr = r2_score(y_train, y_pred_train_svr)
val_r2_svr = r2_score(y_val, y_pred_val_svr)
test_r2_svr = r2_score(y_test, y_pred_test_svr)

print(f"SVR - Training RMSE: {train_rmse_svr:.2f}")
print(f"SVR - Validation RMSE: {val_rmse_svr:.2f}")
print(f"SVR - Test RMSE: {test_rmse_svr:.2f}")

print(f"SVR - Training R^2: {train_r2_svr:.2f}")
print(f"SVR - Validation R^2: {val_r2_svr:.2f}")
print(f"SVR - Test R^2: {test_r2_svr:.2f}")

SVR - Training RMSE: 5891.37
SVR - Validation RMSE: 4932.95
SVR - Test RMSE: 8252.40
SVR - Training R^2: -0.02
SVR - Validation R^2: -0.04
SVR - Test R^2: -0.02

In [85]:
from sklearn.ensemble import AdaBoostRegressor
from sklearn.metrics import mean_squared_error, r2_score

# Initialize and train the AdaBoost Regressor
ada_model = AdaBoostRegressor(random_state=42, n_estimators=200)
ada_model.fit(X_train, y_train)

# Make predictions
y_pred_train_ada = ada_model.predict(X_train)
y_pred_val_ada = ada_model.predict(X_val)
y_pred_test_ada = ada_model.predict(X_test)

# Evaluate the model
train_mse_ada = mean_squared_error(y_train, y_pred_train_ada)
val_mse_ada = mean_squared_error(y_val, y_pred_val_ada)
test_mse_ada = mean_squared_error(y_test, y_pred_test_ada)

train_rmse_ada = train_mse_ada ** 0.5
val_rmse_ada = val_mse_ada ** 0.5
test_rmse_ada = test_mse_ada ** 0.5

train_r2_ada = r2_score(y_train, y_pred_train_ada)
val_r2_ada = r2_score(y_val, y_pred_val_ada)
test_r2_ada = r2_score(y_test, y_pred_test_ada)

print(f"AdaBoost - Training RMSE: {train_rmse_ada:.2f}")
print(f"AdaBoost - Validation RMSE: {val_rmse_ada:.2f}")
print(f"AdaBoost - Test RMSE: {test_rmse_ada:.2f}")

print(f"AdaBoost - Training R^2: {train_r2_ada:.2f}")
print(f"AdaBoost - Validation R^2: {val_r2_ada:.2f}")
print(f"AdaBoost - Test R^2: {test_r2_ada:.2f}")

AdaBoost - Training RMSE: 9776.64
AdaBoost - Validation RMSE: 9973.53
AdaBoost - Test RMSE: 12209.27
AdaBoost - Training R^2: -1.82
AdaBoost - Validation R^2: -3.25
AdaBoost - Test R^2: -1.22

In [105]:
import os
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score


def train_xgb_for_file(file_path):
    data = pd.read_csv(file_path)
    data = data.drop(columns=['Unnamed: 0', 'Date'], errors='ignore')

    target_col = 'Price (₹/ton)' if 'Price (₹/ton)' in data.columns else 'Modal_x0020_Price'
    X_local = data.drop(columns=[target_col])
    y_local = data[target_col]

    # One-hot encode categorical features and align splits
    X_train_l, X_temp_l, y_train_l, y_temp_l = train_test_split(
        X_local, y_local, test_size=0.4, random_state=42
    )
    X_val_l, X_test_l, y_val_l, y_test_l = train_test_split(
        X_temp_l, y_temp_l, test_size=0.5, random_state=42
    )

    X_train_l = pd.get_dummies(X_train_l, drop_first=False)
    X_val_l = pd.get_dummies(X_val_l, drop_first=False).reindex(columns=X_train_l.columns, fill_value=0)
    X_test_l = pd.get_dummies(X_test_l, drop_first=False).reindex(columns=X_train_l.columns, fill_value=0)

    model_l = XGBRegressor(
        objective='reg:squarederror',
        eval_metric='rmse',
        random_state=42,
        n_estimators=300,
        learning_rate=0.05,
        max_depth=6,
    )
    model_l.fit(X_train_l, y_train_l)

    y_pred_train_l = model_l.predict(X_train_l)
    y_pred_val_l = model_l.predict(X_val_l)
    y_pred_test_l = model_l.predict(X_test_l)

    train_rmse_l = mean_squared_error(y_train_l, y_pred_train_l) ** 0.5
    val_rmse_l = mean_squared_error(y_val_l, y_pred_val_l) ** 0.5
    test_rmse_l = mean_squared_error(y_test_l, y_pred_test_l) ** 0.5

    train_r2_l = r2_score(y_train_l, y_pred_train_l)
    val_r2_l = r2_score(y_val_l, y_pred_val_l)
    test_r2_l = r2_score(y_test_l, y_pred_test_l)

    return {
        'Dataset': os.path.basename(file_path),
        'Rows': len(data),
        'Target': target_col,
        'Train_RMSE': round(float(train_rmse_l), 2),
        'Val_RMSE': round(float(val_rmse_l), 2),
        'Test_RMSE': round(float(test_rmse_l), 2),
        'Train_R2': round(float(train_r2_l), 4),
        'Val_R2': round(float(val_r2_l), 4),
        'Test_R2': round(float(test_r2_l), 4),
    }


requested_files = [
    'crop_dataset.csv',
    'crop_dataset_backup.csv',
]

if not os.path.exists('crop_dataset_backup.csv') and os.path.exists('crop_dataset_backup_before_augmentation.csv'):
    requested_files[1] = 'crop_dataset_backup_before_augmentation.csv'

available_files = [f for f in requested_files if os.path.exists(f)]
missing_files = [f for f in requested_files if not os.path.exists(f)]

results = [train_xgb_for_file(f) for f in available_files]

if results:
    print('Model training completed for:')
    for f in available_files:
        print(f'- {f}')
    print()
    print(pd.DataFrame(results))

if missing_files:
    print('\nMissing files:')
    for f in missing_files:
        print(f'- {f}')

Model training completed for:
- crop_dataset.csv
- crop_dataset_backup_before_augmentation.csv

                                       Dataset  Rows  ...  Val_R2  Test_R2
0                             crop_dataset.csv  7611  ...  0.9691   0.9710
1  crop_dataset_backup_before_augmentation.csv  7611  ...  0.9688   0.9663

[2 rows x 9 columns]